version: 2

plan:
  project-key: UDDO
  name: bamboo_ea_plan
  key: EAPL

stages:
  - First stage:
      - JobNumberOne

JobNumberOne:
  tasks:
    - script: |-
        #!/bin/sh
        date
        sleep 120
        echo FINISH
  other:
    pbc:
      image: sanekkurt/bamboo-agent-sidekick-alpine
      size: XSMALL
