version: 2

plan:
  project-key: TEST
  name: second_plan_in_yaml
  key: SEC

stages:
  - First stage:
      - JobNumberOne

JobNumberOne:
  tasks:
    - script: |-
        #!/bin/sh
        date
        sleep 120
        echo FINISH
#  other:
#    pbc:
#      image: docker.io/sanekkurt/bamboo-agent-sidekick-alpine
#      size: XSMALL
